package rs.ac.uns.ftn.sbnz.rules

import rs.ac.uns.ftn.sbnz.models.drools.PropertyWithScore;
import rs.ac.uns.ftn.sbnz.models.drools.ScoredProperties;
import rs.ac.uns.ftn.sbnz.models.*;
import rs.ac.uns.ftn.sbnz.models.Property;
import rs.ac.uns.ftn.sbnz.models.PlaceOfInterest;
import rs.ac.uns.ftn.sbnz.models.drools.SmartSearch;
import rs.ac.uns.ftn.sbnz.models.drools.PropertyInformation;
import rs.ac.uns.ftn.sbnz.models.drools.PersonalInformation;
import rs.ac.uns.ftn.sbnz.models.enums.Interest;
import rs.ac.uns.ftn.sbnz.models.enums.Heating;
import rs.ac.uns.ftn.sbnz.models.enums.PetStatus;
import rs.ac.uns.ftn.sbnz.models.enums.Amenity;
import rs.ac.uns.ftn.sbnz.models.enums.TypeOfPlace;

import java.util.List;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// CATS
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Calculate pet score - CATS" salience 1
    agenda-group "pet_score_calculation"
    when
        $ps: PropertyWithScore(
            scaler.getFiredRules() not contains "Calculate pet score - CATS",
            property.getAllowedPets() contains PetStatus.CATS
         );
    then
        System.out.println(String.format("Adding CATS pet score for %s", $ps.getProperty().getId()));

        double score = 1.5 * $ps.getScaler().getPetScale();
        $ps.setScore($ps.getScore() + score);

        System.out.println(String.format("Score for %s is %s \n", $ps.getProperty().getId(), $ps.getScore()));
        $ps.getScaler().getFiredRules().add("Calculate pet score - CATS");
        update($ps);
end

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DOGS
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Calculate pet score - DOGS" salience 1
    agenda-group "pet_score_calculation"
    when
        $ps: PropertyWithScore(
            scaler.getFiredRules() not contains "Calculate pet score - DOGS",
            property.getAllowedPets() contains PetStatus.DOGS
         );
    then
        System.out.println(String.format("Adding DOGS pet score for %s", $ps.getProperty().getId()));

        double score = 1.5 * $ps.getScaler().getPetScale();
        $ps.setScore($ps.getScore() + score);

        System.out.println(String.format("Score for %s is %s \n", $ps.getProperty().getId(), $ps.getScore()));
        $ps.getScaler().getFiredRules().add("Calculate pet score - DOGS");
        update($ps);
end

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IN_AQUARIUM
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Calculate pet score - IN_AQUARIUM" salience 1
    agenda-group "pet_score_calculation"
    when
        $ps: PropertyWithScore(
            scaler.getFiredRules() not contains "Calculate pet score - IN_AQUARIUM",
            property.getAllowedPets() contains PetStatus.IN_AQUARIUM
         );
    then
        System.out.println(String.format("Adding IN_AQUARIUM pet score for %s", $ps.getProperty().getId()));

        double score = 0.5 * $ps.getScaler().getPetScale();
        $ps.setScore($ps.getScore() + score);

        System.out.println(String.format("Score for %s is %s \n", $ps.getProperty().getId(), $ps.getScore()));
        $ps.getScaler().getFiredRules().add("Calculate pet score - IN_AQUARIUM");
        update($ps);
end

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IN_TERRARIUM
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Calculate pet score - IN_TERRARIUM" salience 1
    agenda-group "pet_score_calculation"
    when
        $ps: PropertyWithScore(
            scaler.getFiredRules() not contains "Calculate pet score - IN_TERRARIUM",
            property.getAllowedPets() contains PetStatus.IN_TERRARIUM
         );
    then
        System.out.println(String.format("Adding IN_TERRARIUM pet score for %s", $ps.getProperty().getId()));

        double score = 0.5 * $ps.getScaler().getPetScale();
        $ps.setScore($ps.getScore() + score);

        System.out.println(String.format("Score for %s is %s \n", $ps.getProperty().getId(), $ps.getScore()));
        $ps.getScaler().getFiredRules().add("Calculate pet score - IN_TERRARIUM");
        update($ps);
end