package rs.ac.uns.ftn.sbnz.rules

import rs.ac.uns.ftn.sbnz.models.drools.PropertyWithScore;
import rs.ac.uns.ftn.sbnz.models.drools.ScoredProperties;
import rs.ac.uns.ftn.sbnz.models.*;
import rs.ac.uns.ftn.sbnz.models.Property;
import rs.ac.uns.ftn.sbnz.models.PlaceOfInterest;
import rs.ac.uns.ftn.sbnz.web.dto.v1.SmartSearchDTO;
import rs.ac.uns.ftn.sbnz.web.dto.v1.PropertyInformationDTO;
import rs.ac.uns.ftn.sbnz.web.dto.v1.PersonalInformationDTO;
import rs.ac.uns.ftn.sbnz.models.enums.Interest;
import rs.ac.uns.ftn.sbnz.models.enums.Heating;
import rs.ac.uns.ftn.sbnz.models.enums.PetStatus;
import rs.ac.uns.ftn.sbnz.models.enums.Amenity;
import rs.ac.uns.ftn.sbnz.models.enums.TypeOfPlace;

import java.util.List;

rule "Calculate heating score" salience 1
    when
        $ps: PropertyWithScore(scaler.getFiredRules() not contains "Calculate heating score");
        $sp: ScoredProperties();
    then
        System.out.println(String.format("Calculating heating score for %s", $ps.getProperty().getId()));
        double score = 0.0;

        if ($ps.getProperty().getHeating().equals(Heating.FURNACE))
            score += 1 * $ps.getScaler().getHeatingScale();
        if ($ps.getProperty().getHeating().equals(Heating.BOILER))
            score += 2 * $ps.getScaler().getHeatingScale();
        if ($ps.getProperty().getHeating().equals(Heating.HEAT_PUMP))
            score += 3 * $ps.getScaler().getHeatingScale();
        if ($ps.getProperty().getHeating().equals(Heating.HYBRID))
            score += 4 * $ps.getScaler().getHeatingScale();
        if ($ps.getProperty().getHeating().equals(Heating.DUCTLESS_MINI_SPLITS))
            score += 5 * $ps.getScaler().getHeatingScale();
        if ($ps.getProperty().getHeating().equals(Heating.RADIANT))
            score += 6 * $ps.getScaler().getHeatingScale();

        $ps.setScore($ps.getScore() + score);
        System.out.println(String.format("Score for %s is %s \n", $ps.getProperty().getId(), $ps.getScore()));
        $ps.getScaler().getFiredRules().add("Calculate heating score");
        update($ps);
end